import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Continuity, detectLimit } from "../servidor/continuity.ts";
import { parseQuota } from "../servidor/codex-quota.ts";

assert.equal(detectLimit("You've hit your usage limit. Try again later.")?.state, "blocked");
assert.equal(detectLimit("\x1b[31mUsage limit reached\x1b[0m")?.state, "blocked");
assert.equal(detectLimit("RESOURCE_EXHAUSTED: quota exhausted")?.state, "blocked");
assert.equal(detectLimit("5h limit: 9% left")?.remaining, 9);
assert.equal(detectLimit("context: 2% left"), null);
assert.equal(detectLimit("5h limit: 80% left"), null);
assert.equal(detectLimit('const msg = "Usage limit reached"'), null);
assert.equal(detectLimit("Explain how rate limits work."), null);
assert.equal(parseQuota({ rateLimits: { limitId: "codex", primary: { usedPercent: 95, resetsAt: 123 }, secondary: { usedPercent: 50 } } })?.remaining, 5);
assert.equal(parseQuota({ rateLimits: { primary: { usedPercent: 20 }, secondary: { usedPercent: 90 } } })?.remaining, 10);
assert.equal(parseQuota({}), null);
assert.equal(parseQuota({ rateLimits: { primary: { usedPercent: -20 } } }), null);
const dir = mkdtempSync(join(tmpdir(), "cockpit-continuity-"));
const store = new Continuity(dir);
store.record("m1", "p1", "input", "Preserve preto e azul.");
store.record("m1", "p1", "output", "\x1b[32mTeste passou\x1b[0m");
store.checkpoint("m1", "Header pronto. Falta revisar formulários.");
const restored = new Continuity(dir);
const prompt = restored.handoff("m1", "Melhorar interface", [{ paneId: "p2", tarefa: "formulários" }]);
assert.match(prompt, /Header pronto/);
assert.match(prompt, /Melhorar interface/);
assert.match(prompt, /p2/);
assert.match(prompt, /history.jsonl/);
assert.match(readFileSync(join(dir, "m1", "history.jsonl"), "utf8"), /Preserve preto e azul/);
assert.doesNotMatch(readFileSync(join(dir, "m1", "history.jsonl"), "utf8"), /\\u001b/);
assert.throws(() => store.path("../outside"));
assert.match(store.readCheckpoint("m2"), /Ainda não/);
console.log("PASS: explicit limit signals, false positives, structured Codex quotas, durable mission context and mission isolation.");
